"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from django.urls import reverse_lazy


def _env(nome, padrao=""):
    return os.environ.get(nome, padrao)


def _carregar_env_dev():
    """Loads .env.dev when running locally. Never present in the image."""
    caminho = Path(__file__).resolve().parent.parent / ".env.dev"
    if not caminho.exists():
        return
    for linha in caminho.read_text().splitlines():
        linha = linha.strip()
        if linha and not linha.startswith("#") and "=" in linha:
            chave, valor = linha.split("=", 1)
            os.environ.setdefault(chave.strip(), valor.strip().strip('"'))


_carregar_env_dev()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w&oc44ceoq6!fy(@c3*yws)pj9w6%^jijl-@l8ik!ijnjon8xv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Unfold must precede django.contrib.admin: it overrides the admin templates.
    "unfold",
    "unfold.contrib.filters",
    "gado",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "HOST": _env("PGHOST", "localhost"),
        "PORT": _env("PGPORT", "5432"),
        "NAME": _env("PGDATABASE", "tiao_database"),
        "USER": _env("PGUSER", "tiao_user"),
        "PASSWORD": _env("PGPASSWORD"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "pt-br"

# The farm is in Sao Paulo; the container is not. `date.today()` in UTC
# rolls over at 21:00 local, which is what made the old viewer render an
# empty page every evening -- exactly when Jader would open it.
TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# Unfold -- Tailwind theme over the stock Django admin. Everything it shows is
# still generated by Django; this only sets identity and the sidebar order.
UNFOLD = {
    "SITE_TITLE": "Pecuária Batistela",
    "SITE_HEADER": "Pecuária Batistela",
    "SITE_SYMBOL": "pets",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,
    "SIDEBAR": {
        "show_search": True,
        "navigation": [
            {
                "title": "Rebanho",
                "items": [
                    {"title": "Animais", "icon": "pets",
                     "link": reverse_lazy("admin:gado_animal_changelist")},
                    {"title": "Pesagens", "icon": "scale",
                     "link": reverse_lazy("admin:gado_pesagem_changelist")},
                    {"title": "Propriedades", "icon": "grass",
                     "link": reverse_lazy("admin:gado_propriedade_changelist")},
                ],
            },
            {
                "title": "Dinheiro",
                "items": [
                    {"title": "Compras", "icon": "shopping_cart",
                     "link": reverse_lazy("admin:gado_compra_changelist")},
                    {"title": "Vendas", "icon": "sell",
                     "link": reverse_lazy("admin:gado_venda_changelist")},
                    {"title": "Despesas", "icon": "receipt_long",
                     "link": reverse_lazy("admin:gado_despesa_changelist")},
                    {"title": "Cotações", "icon": "trending_up",
                     "link": reverse_lazy("admin:gado_cotacao_changelist")},
                ],
            },
            {
                "title": "Pessoas",
                "items": [
                    {"title": "Fornecedores", "icon": "local_shipping",
                     "link": reverse_lazy("admin:gado_fornecedor_changelist")},
                    {"title": "Compradores", "icon": "handshake",
                     "link": reverse_lazy("admin:gado_comprador_changelist")},
                ],
            },
        ],
    },
}
