"""The management side -- this is for Matheus, not for Jader.

Jader gets purpose-built read-only pages elsewhere. No admin, however well
themed, is the right thing to hand a 70-year-old rancher on a phone.

Everything here is generated by Django from the models: list, pagination,
filters, search, forms. What is written below is only which columns to show and
how to group them.
"""

from django.contrib import admin
from django.db.models import Max, Sum
from django.utils.html import format_html
from unfold.admin import ModelAdmin, TabularInline

from .models import (
    Animal, Comprador, Compra, Contraparte, Cotacao, Despesa, Fornecedor,
    Movimentacao, Pesagem, Propriedade, Venda,
)

admin.site.site_header = "Pecuária Batistela"
admin.site.site_title = "Pecuária Batistela"
admin.site.index_title = "Gerenciamento"


def _reais(v):
    if v is None:
        return "—"
    return f"R$ {v:,.2f}".translate(str.maketrans(",.", ".,"))


class PesagemInline(TabularInline):
    model = Pesagem
    extra = 0
    fields = ("data", "peso_kg", "observacoes")
    ordering = ("-data",)


class DespesaInline(TabularInline):
    model = Despesa
    extra = 0
    fields = ("data", "tipo", "valor", "detalhes")
    ordering = ("-data",)


@admin.register(Animal)
class AnimalAdmin(ModelAdmin):
    list_display = ("brinco", "categoria", "sexo", "propriedade",
                    "peso_display", "arrobas_display", "valor_display",
                    "despesas_display", "situacao")
    list_filter = ("categoria", "sexo", "propriedade", "raca")
    search_fields = ("brinco", "observacoes")
    autocomplete_fields = ("compra", "venda", "propriedade")
    inlines = [PesagemInline, DespesaInline]
    list_per_page = 50
    fieldsets = (
        ("Identificação", {"fields": ("brinco", "categoria", "sexo", "raca",
                                      "pelagem", "data_nascimento")}),
        ("Onde está", {"fields": ("propriedade",)}),
        ("Compra", {"fields": ("compra", "valor_compra")}),
        ("Venda", {"fields": ("venda",)}),
        ("Outros", {"fields": ("observacoes",)}),
    )

    def get_queryset(self, request):
        # Without these, the herd list runs two queries per row.
        return (super().get_queryset(request)
                .select_related("propriedade", "compra", "venda")
                .prefetch_related("pesagens", "despesas")
                .annotate(_ultima=Max("pesagens__data"),
                          _despesas=Sum("despesas__valor")))

    @admin.display(description="peso", ordering="_ultima")
    def peso_display(self, obj):
        kg = obj.peso_atual_kg
        return f"{kg:.0f} kg" if kg is not None else "—"

    @admin.display(description="em @")
    def arrobas_display(self, obj):
        a = obj.peso_arrobas
        return f"{a:.2f} @".replace(".", ",") if a is not None else "—"

    @admin.display(description="valor atual")
    def valor_display(self, obj):
        return _reais(obj.valor_atual)

    @admin.display(description="despesas", ordering="_despesas")
    def despesas_display(self, obj):
        return _reais(obj._despesas)

    @admin.display(description="situação")
    def situacao(self, obj):
        cor, texto = ("#b45309", "vendido") if obj.venda_id else ("#15803d", "no pasto")
        return format_html('<b style="color:{}">{}</b>', cor, texto)


@admin.register(Pesagem)
class PesagemAdmin(ModelAdmin):
    list_display = ("animal", "data", "peso_kg")
    list_filter = ("data",)
    search_fields = ("animal__brinco",)
    autocomplete_fields = ("animal",)
    date_hierarchy = "data"


@admin.register(Despesa)
class DespesaAdmin(ModelAdmin):
    list_display = ("animal", "data", "tipo", "valor_display", "detalhes")
    list_filter = ("tipo", "data")
    search_fields = ("animal__brinco", "detalhes")
    autocomplete_fields = ("animal",)
    date_hierarchy = "data"

    @admin.display(description="valor", ordering="valor")
    def valor_display(self, obj):
        return _reais(obj.valor)


class MovimentacaoAdminBase(ModelAdmin):
    list_display = ("data", "comprador", "quantidade", "valor_display",
                    "por_cabeca_display", "observacoes")
    list_filter = ("data",)
    search_fields = ("comprador__nome", "observacoes")
    autocomplete_fields = ("comprador",)
    date_hierarchy = "data"
    # `tipo` is set by the proxy's save(); showing it would only invite a
    # mismatch between the section you are in and the value you typed.
    exclude = ("tipo",)

    @admin.display(description="valor", ordering="valor")
    def valor_display(self, obj):
        return _reais(obj.valor)

    @admin.display(description="por cabeça")
    def por_cabeca_display(self, obj):
        return _reais(obj.valor_por_cabeca)


@admin.register(Compra)
class CompraAdmin(MovimentacaoAdminBase):
    pass


@admin.register(Venda)
class VendaAdmin(MovimentacaoAdminBase):
    pass


class ContraparteAdminBase(ModelAdmin):
    list_display = ("nome", "cidade", "telefone", "quantas")
    search_fields = ("nome", "cidade")
    exclude = ("tipo",)

    @admin.display(description="negócios")
    def quantas(self, obj):
        return obj.movimentacoes.count()


@admin.register(Fornecedor)
class FornecedorAdmin(ContraparteAdminBase):
    pass


@admin.register(Comprador)
class CompradorAdmin(ContraparteAdminBase):
    pass


@admin.register(Propriedade)
class PropriedadeAdmin(ModelAdmin):
    list_display = ("nome", "quantos_animais", "observacoes")
    search_fields = ("nome",)

    @admin.display(description="cabeças")
    def quantos_animais(self, obj):
        return obj.animais.count()


@admin.register(Cotacao)
class CotacaoAdmin(ModelAdmin):
    """Written by the 19:00 cron. Editable, but you should not need to."""

    list_display = ("data_pregao", "categoria", "praca", "avista_display",
                    "trinta_display")
    list_filter = ("categoria", "praca")
    date_hierarchy = "data_pregao"

    @admin.display(description="bruto à vista", ordering="bruto_a_vista")
    def avista_display(self, obj):
        return _reais(obj.bruto_a_vista) + ("/kg" if obj.por_quilo else "/@")

    @admin.display(description="bruto 30 dias", ordering="bruto_30d")
    def trinta_display(self, obj):
        return _reais(obj.bruto_30d) + ("/kg" if obj.por_quilo else "/@")


# Movimentacao and Contraparte must be registered for autocomplete_fields to
# work against them (Django checks the target admin for search_fields), but
# they must NOT appear in the index or every deal would be listed twice --
# once here and once under its proxy. Empty model perms hides them from the
# index while keeping the autocomplete endpoint alive.


class _SoParaAutocomplete(ModelAdmin):
    def get_model_perms(self, request):
        return {}


@admin.register(Movimentacao)
class MovimentacaoAdmin(_SoParaAutocomplete):
    search_fields = ("comprador__nome", "observacoes", "tipo")


@admin.register(Contraparte)
class ContraparteAdmin(_SoParaAutocomplete):
    search_fields = ("nome", "cidade")
