all:
  hosts:
    localhost:
      ansible_connection: local

  children:
    proxmox:
      vars:
        ansible_user: root
        ansible_connection: ssh
        ansible_ssh_private_key_file: ~/.ssh/homelab

      hosts:
        pve: {}
        media: {}
        infra: {}
        database: {}
        minecraft: {}
        tools: {}
        n8n: {}
        tailscale: {}
        authelia: {}
        minecraft-be: {}

    unmanaged:
      vars:
        ansible_connection: ssh
        ansible_user: root
        ansible_ssh_private_key_file: ~/.ssh/homelab
      hosts:
        ha:
          ansible_user: hassio
        openwebui: {}

    monitored_nodes:
      hosts:
        pve: {}
        media: {}
        database: {}
        minecraft: {}
        tools: {}
        tailscale: {}
        openwebui: {}

    docker_monitored:
      hosts:
        media: {}
        tools: {}
