---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Start and enable minecraft service
  ansible.builtin.systemd:
    name: minecraft
    state: started
    enabled: true
  become: true
