---
- name: Create RabbitMQ compose directory
  ansible.builtin.file:
    path: "{{ rabbitmq_compose_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Create RabbitMQ data directory
  ansible.builtin.file:
    path: "{{ rabbitmq_data_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Deploy RabbitMQ docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ rabbitmq_compose_dir }}/docker-compose.yml"
    owner: root
    group: root
    mode: "0600"
  notify: Restart rabbitmq

- name: Deploy RabbitMQ using docker-compose
  community.docker.docker_compose_v2:
    project_src: "{{ rabbitmq_compose_dir }}"
    state: present
    pull: always
