all:
  hosts:
    localhost:
      ansible_connection: local

  children:
    racknerd:
      hosts:
        racknerd_vm0:
          ansible_host: "{{ racknerd_vm0_ip }}"
          ansible_connection: ssh
          ansible_user: "{{ racknerd_vm0_user }}"
          ansible_ssh_private_key_file: "{{ racknerd_vm0_ssh_key }}"