---
all:
  hosts:
    localhost:
      ansible_connection: local

  children:
    racknerd:
      hosts:
        racknerd_vm0:
          ansible_host: 204.152.223.118
          ansible_connection: ssh
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/homelab
