# Generated by Django 6.1 on 2026-08-30 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contraparte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(verbose_name='nome')),
                ('tipo', models.TextField(verbose_name='tipo')),
                ('telefone', models.TextField(blank=True, null=True, verbose_name='telefone')),
                ('cidade', models.TextField(blank=True, null=True, verbose_name='cidade')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'contraparte',
                'verbose_name_plural': 'contrapartes',
                'db_table': 'compradores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('boi', 'boi gordo'), ('novilha', 'novilha'), ('vaca', 'vaca gorda')], max_length=16, verbose_name='categoria')),
                ('praca', models.TextField(verbose_name='praça')),
                ('data_pregao', models.DateField(verbose_name='data do pregão')),
                ('bruto_a_vista', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='bruto à vista')),
                ('bruto_30d', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='bruto 30 dias')),
                ('por_quilo', models.BooleanField(default=False, verbose_name='cotada por quilo')),
                ('coletado_em', models.DateTimeField(auto_now_add=True, verbose_name='coletado em')),
            ],
            options={
                'verbose_name': 'cotação',
                'verbose_name_plural': 'cotações',
                'db_table': 'cotacoes',
                'ordering': ['-data_pregao', 'categoria'],
                'unique_together': {('categoria', 'praca', 'data_pregao')},
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.TextField(verbose_name='tipo')),
                ('data', models.DateField(verbose_name='data')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='valor')),
                ('quantidade', models.IntegerField(blank=True, null=True, verbose_name='quantidade')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('comprador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='movimentacoes', to='gado.contraparte', verbose_name='contraparte')),
            ],
            options={
                'verbose_name': 'movimentação',
                'verbose_name_plural': 'movimentações',
                'db_table': 'compras',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brinco', models.TextField(unique=True, verbose_name='brinco')),
                ('raca', models.TextField(blank=True, null=True, verbose_name='raça')),
                ('categoria', models.TextField(blank=True, null=True, verbose_name='categoria')),
                ('sexo', models.TextField(blank=True, null=True, verbose_name='sexo')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('valor_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='valor de compra')),
                ('pelagem', models.TextField(blank=True, null=True, verbose_name='pelagem')),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='animais_comprados', to='gado.movimentacao', verbose_name='compra')),
            ],
            options={
                'verbose_name': 'animal',
                'verbose_name_plural': 'animais',
                'db_table': 'animais',
                'ordering': ['brinco'],
            },
        ),
        migrations.CreateModel(
            name='Pesagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data')),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='peso (kg)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pesagens', to='gado.animal', verbose_name='animal')),
            ],
            options={
                'verbose_name': 'pesagem',
                'verbose_name_plural': 'pesagens',
                'db_table': 'pesagens',
                'ordering': ['-data'],
                'unique_together': {('animal', 'data')},
            },
        ),
    ]
