# Generated by Django 6.1 on 2026-08-30 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(unique=True, verbose_name='nome')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'propriedade',
                'verbose_name_plural': 'propriedades',
                'db_table': 'propriedades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
            ],
            options={
                'verbose_name': 'compra',
                'verbose_name_plural': 'compras',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gado.movimentacao',),
        ),
        migrations.CreateModel(
            name='Comprador',
            fields=[
            ],
            options={
                'verbose_name': 'comprador',
                'verbose_name_plural': 'compradores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gado.contraparte',),
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
            ],
            options={
                'verbose_name': 'fornecedor',
                'verbose_name_plural': 'fornecedores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gado.contraparte',),
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
            ],
            options={
                'verbose_name': 'venda',
                'verbose_name_plural': 'vendas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gado.movimentacao',),
        ),
        migrations.AddField(
            model_name='animal',
            name='venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animais_vendidos', to='gado.movimentacao', verbose_name='venda'),
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor')),
                ('data', models.DateField(verbose_name='data')),
                ('tipo', models.CharField(choices=[('VETERINARIA', 'veterinária'), ('ALIMENTACAO', 'alimentação'), ('TRANSPORTE', 'transporte'), ('MEDICACAO', 'medicação'), ('OUTRO', 'outro')], max_length=16, verbose_name='tipo')),
                ('detalhes', models.TextField(blank=True, null=True, verbose_name='detalhes')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='gado.animal', verbose_name='animal')),
            ],
            options={
                'verbose_name': 'despesa',
                'verbose_name_plural': 'despesas',
                'db_table': 'despesas',
                'ordering': ['-data'],
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='propriedade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animais', to='gado.propriedade', verbose_name='propriedade'),
        ),
    ]
