# Generated by Django 6.1 on 2026-08-30 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gado', '0003_propriedades_iniciais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesagem',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesagens', to='gado.animal', verbose_name='animal'),
        ),
    ]
