# Generated by Django 6.1 on 2026-08-30 03:24

from django.db import migrations, models



def normalizar(apps, schema_editor):
    """Brings existing rows onto the enum before the CHECK is added.

    The seven live animals were written by the bot as sexo='fêmea', with the
    accent. Storage is now ASCII ('femea'), so adding the constraint first would
    fail on real data.
    """
    Animal = apps.get_model("gado", "Animal")
    from gado.models import normalizar_categoria, normalizar_sexo
    for a in Animal.objects.all():
        cat, sx = normalizar_categoria(a.categoria), normalizar_sexo(a.sexo)
        if cat != a.categoria or sx != a.sexo:
            a.categoria, a.sexo = cat, sx
            Animal.objects.filter(pk=a.pk).update(categoria=cat, sexo=sx)


def desnormalizar(apps, schema_editor):
    # Nothing to undo: 'femea' is valid free text too.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('gado', '0004_alter_pesagem_animal'),
    ]

    operations = [
        migrations.RunPython(normalizar, desnormalizar),
        migrations.AlterField(
            model_name='animal',
            name='categoria',
            field=models.CharField(blank=True, choices=[('bezerro', 'bezerro'), ('garrote', 'garrote'), ('novilho', 'novilho'), ('boi', 'boi'), ('touro', 'touro'), ('bezerra', 'bezerra'), ('novilha', 'novilha'), ('vaca', 'vaca')], max_length=16, null=True, verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.CharField(blank=True, choices=[('macho', 'macho'), ('femea', 'fêmea')], max_length=16, null=True, verbose_name='sexo'),
        ),
        migrations.AddConstraint(
            model_name='animal',
            constraint=models.CheckConstraint(condition=models.Q(('sexo__in', ['macho', 'femea']), ('sexo__isnull', True), _connector='OR'), name='animais_sexo_valido'),
        ),
        migrations.AddConstraint(
            model_name='animal',
            constraint=models.CheckConstraint(condition=models.Q(('categoria__in', ['bezerro', 'garrote', 'novilho', 'boi', 'touro', 'bezerra', 'novilha', 'vaca']), ('categoria__isnull', True), _connector='OR'), name='animais_categoria_valida'),
        ),
    ]
