# Generated by Django 6.1 on 2026-08-30 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gado', '0005_enums_categoria_e_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotacao',
            name='por_quilo',
        ),
    ]
