# Generated by Django 6.1 on 2026-08-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gado', '0006_remove_por_quilo'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='referencia',
            field=models.TextField(blank=True, help_text='Como o patrão chama o bicho quando não tem brinco', null=True, verbose_name='referência'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='brinco',
            field=models.TextField(blank=True, null=True, unique=True, verbose_name='brinco'),
        ),
        migrations.AddConstraint(
            model_name='animal',
            constraint=models.CheckConstraint(condition=models.Q(('brinco__isnull', False), ('referencia__isnull', False), _connector='OR'), name='animais_identificavel'),
        ),
    ]
