# Generated by Django 6.1 on 2026-08-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gado', '0007_animal_sem_brinco'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='peso_venda',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso no dia da venda, se diferente da última pesagem', max_digits=8, null=True, verbose_name='peso na venda'),
        ),
        migrations.AddField(
            model_name='animal',
            name='valor_venda',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quanto esta cabeça saiu, quando ele sabe o valor por cabeça', max_digits=12, null=True, verbose_name='valor de venda'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='preco_arroba',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quando o negócio foi fechado por arroba', max_digits=10, null=True, verbose_name='preço da arroba'),
        ),
    ]
