# Generated by Django 6.1 on 2026-08-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gado', '0008_venda_por_arroba'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='preco_arroba_venda',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quando esta cabeça saiu por arroba diferente da do negócio (magra, meia carne)', max_digits=10, null=True, verbose_name='preço da arroba desta cabeça'),
        ),
    ]
