- name: Prepare and install PostgreSQL "{{ postgresql_version }}"
  hosts: database
  become: true

  vars:
    pg_codename: "bookworm-pgdg"
    pg_key_url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    pg_keyring: "/usr/share/keyrings/pgdg-archive-keyring.gpg"
    pg_repo: "deb [signed-by={{ pg_keyring }}] https://apt.postgresql.org/pub/repos/apt {{ pg_codename }} main"

  pre_tasks:
    - block:
        - name: Ensure GnuPG is installed (for apt_key)
          apt:
            name: gnupg
            state: present

        - name: Add PostgreSQL APT key
          apt_key:
            url: "{{ pg_key_url }}"
            keyring: "{{ pg_keyring }}"
            state: present

        - name: Add PostgreSQL APT repository
          apt_repository:
            repo: "{{ pg_repo }}"
            filename: pgdg
            
        - name: Update apt cache
          apt:
            update_cache: yes

      tags: postgresql_repo_setup

  roles:
    - role: geerlingguy.postgresql
      vars:
       postgres_users_no_log: false
       postgresql_users:
        - name: fresh_rss_user
          password: "{{ vault.database.fresh_rss_user_pw }}" 
        - name: n8n_user
          password: "{{ vault.database.n8n_user_pw }}"
        - name: calcom_user
          password: "{{ vault.database.calcom_user_pw }}"
        - name: invoice_ninja_user
          password: "{{ vault.database.n8n_user_pw }}"

      postgresql_databases:
        - name: fresh_rss_database
          owner: fresh_rss_user
        - name: n8n_database
          owner: n8n_user
        - name: calcom_database
          owner: calcom_user
        - name: invoice_ninja_database
          owner: invoice_ninja_user
      

  tags: postgresql_install

- name: Prepare and install InfluxDB
  hosts: database
  become: true

  roles:
    - role: influxdb
      vars:
        influxdb_databases:
          - name: "homeassistant"
          - name: "localtraefik"
  tags: influxdb_install

- name: Prepare and install Redis
  hosts: database
  become: true

  roles:
    - role: geerlingguy.redis

  tags: redis_install
