---
- name: Prepare and install PostgreSQL
  hosts: database
  become: true
  gather_facts: true

  pre_tasks:
    - tags: postgresql_repo_setup

      block:
        - name: Ensure GnuPG is installed (for apt_key)
          ansible.builtin.apt:
            name: gnupg
            state: present

        - name: Add PostgreSQL APT key
          ansible.builtin.apt_key:
            url: "{{ postgresql_repo.key_url }}"
            keyring: "{{ postgresql_repo.keyring }}"
            state: present

        - name: Add PostgreSQL APT repository
          ansible.builtin.apt_repository:
            repo: "{{ postgresql_repo.repo }}"
            filename: pgdg

        - name: Update apt cache
          ansible.builtin.apt:
            update_cache: true

  roles:
    - role: geerlingguy.postgresql
      vars:
        postgres_users_no_log: false

  tags: postgresql_install

- name: Prepare and install InfluxDB
  hosts: database
  become: true
  gather_facts: true

  roles:
    - role: influxdb

  tags: influxdb_install

- name: Prepare and install Redis
  hosts: database
  become: true
  gather_facts: true

  roles:
    - role: geerlingguy.redis

  tags: redis_install

- name: Deploy journal log collection
  hosts: database
  become: true
  gather_facts: true
  roles:
    - role: promtail_journal
      promtail_journal_units:
        - postgresql@17-main.service
        - redis-server.service
  tags: promtail
