- name: "Install Traefik"
  hosts: infra
  gather_facts: true
  become: true
  roles:
    - traefik

- name: "Configure Traefik services"
  hosts: infra
  become: true
  gather_facts: true
  tasks:
    - name: "Configure {{ item.service_name | default(item.filename) }}"
      ansible.builtin.include_role:
        name: traefik
        tasks_from: configure_service
      vars:
        traefik_conf: "{{ item }}"
      loop: "{{ traefik_services }}"
      loop_control:
        label: "{{ item.service_name | default(item.filename) }}"
  tags:
    - traefik_config
