---
- name: "Deploy *arr media stack under Docker"
  hosts: media
  gather_facts: true
  become: true
  roles:
    - arr_stack

- name: "Adds samba for homeshare"
  hosts: media
  gather_facts: true
  become: true
  roles:
    - samba_share

- name: "Deploy Navidrome music server"
  hosts: media
  gather_facts: true
  become: true
  roles:
    - navidrome

- name: "Deploy tiddl-manager Tidal subscription syncer"
  hosts: media
  gather_facts: true
  become: true
  roles:
    - tiddl_manager

- name: "Deploy Aria2 download manager"
  hosts: media
  gather_facts: true
  become: true
  roles:
    - aria2

- name: "Deploy JDownloader 2"
  hosts: media
  gather_facts: true
  become: true
  roles:
    - jdownloader
