---
- name: Setup minecraft server
  hosts: minecraft
  gather_facts: true
  become: true

  roles:
    - minecraft_server

- name: Deploy journal log collection
  hosts: minecraft
  become: true
  gather_facts: true
  roles:
    - role: promtail_journal
      promtail_journal_units:
        - minecraft.service
