---
- name: Configure tools VM
  hosts: tools
  become: true
  gather_facts: true
  roles:
    - geerlingguy.docker
    - actual_budget
    - portainer
    - platypus
    - role: databasus
      tags: databasus_install
