- name: check if Proxmox VE storage '{{ pve_vmstorage_storage_id }}' exists
  ansible.builtin.command:
    cmd: "pvesm status --storage {{ pve_vmstorage_storage_id }}"
  register: vmstorage_pvesm_status
  changed_when: false
  failed_when: false
  become: true

- name: add '{{ pve_vmstorage_storage_id }}' directory storage if missing
  ansible.builtin.command:
    cmd: >-
      pvesm add dir {{ pve_vmstorage_storage_id }}
      --path {{ pve_vmstorage_mount_point }}
      --content {{ pve_vmstorage_content_types }}
      --shared {{ pve_vmstorage_shared }}
      {{ '--nodes ' + pve_vmstorage_nodes if pve_vmstorage_nodes else '' }}
      {{ '--disable 0' if pve_vmstorage_enable else '--disable 1' }}
  when: vmstorage_pvesm_status.rc != 0
  become: true
  changed_when: true

- name: update '{{ pve_vmstorage_storage_id }}' properties if it exists
  ansible.builtin.command:
    cmd: >-
      pvesm set {{ pve_vmstorage_storage_id }}
      --content {{ pve_vmstorage_content_types }}
      --shared {{ pve_vmstorage_shared }}
      {{ '--nodes ' + pve_vmstorage_nodes if pve_vmstorage_nodes else '' }}
      {{ '--disable 0' if pve_vmstorage_enable else '--disable 1' }}
  when: vmstorage_pvesm_status.rc == 0
  register: pve_vmstorage_pvesm_set
  become: true
  changed_when: "'no changes' not in (pve_vmstorage_pvesm_set.stdout_lines | join(' '))"
  