---
- name: "Check if Proxmox VE storage exists: '{{ pve_vmstorage_storage_id }}'"
  ansible.builtin.command:
    cmd: "pvesm status --storage {{ pve_vmstorage_storage_id }}"
  register: pve_vmstorage_pvesm_status
  changed_when: false
  failed_when: false
  become: true

- name: "Add directory storage if missing: '{{ pve_vmstorage_storage_id }}'"
  ansible.builtin.command:
    cmd: >-
      pvesm add dir {{ pve_vmstorage_storage_id }}
      --path {{ pve_vmstorage_mount_point }}
      --content {{ pve_vmstorage_content_types }}
      --shared {{ pve_vmstorage_shared }}
      {{ '--nodes ' + pve_vmstorage_nodes if pve_vmstorage_nodes else '' }}
      {{ '--disable 0' if pve_vmstorage_enable else '--disable 1' }}
  when: pve_vmstorage_pvesm_status.rc != 0
  become: true
  changed_when: true

- name: "Update properties if storage exists: '{{ pve_vmstorage_storage_id }}'"
  ansible.builtin.command:
    cmd: >-
      pvesm set {{ pve_vmstorage_storage_id }}
      --content {{ pve_vmstorage_content_types }}
      --shared {{ pve_vmstorage_shared }}
      {{ '--nodes ' + pve_vmstorage_nodes if pve_vmstorage_nodes else '' }}
      {{ '--disable 0' if pve_vmstorage_enable else '--disable 1' }}
  when: pve_vmstorage_pvesm_status.rc == 0
  register: pve_vmstorage_pvesm_set
  become: true
  changed_when: "'no changes' not in (pve_vmstorage_pvesm_set.stdout_lines | join(' '))"
