traefik_version: "v3.4.1"
traefik_bin_path: /usr/local/bin/traefik
traefik_config_path: /etc/traefik
traefik_config_file: "{{ traefik_config_path }}/traefik.yml"
traefik_service_file: /etc/systemd/system/traefik.service
traefik_log_file: /var/log/traefik.log
traefik_access_log_file: /var/log/traefik_access.log
traefik_acme_email: "{{ admin_email }}"
traefik_cloudflare_email: "{{ admin_email }}"
traefik_cloudflare_token: "{{ vault.infra.traefik_cloudflare_token }}"
traefik_dashboard_credentials: "{{ vault.infra.traefik_dashboard_credentials | default('admin:admin') }}"
traefik_cert_resolver_name: cloudflareLocal
traefik_local_domain: "{{ local_domain }}"

# Extra entrypoints beyond http/https
traefik_extra_entrypoints:
  - name: minecraft
    port: 25565

# InfluxDB metrics
traefik_influxdb_enabled: true
traefik_influxdb_address: "http://{{ hostvars['database'].ansible_host }}:8181"
traefik_influxdb_token: "{{ vault.infra.traefik_influxdb_token }}"
traefik_influxdb_bucket: localtraefik
traefik_influxdb_org: localtraefik
traefik_influxdb_push_interval: 10s
traefik_influxdb_environment: local
