checkmk_server_version: "2.4.0p3"
checkmk_server_edition: "{{ checkmk.edition }}"

checkmk_server_configure_firewall: 'true'

checkmk_server_sites:
  - name: "{{ checkmk.site}}"
    version: "{{ checkmk_server_version }}"
    update_conflict_resolution: abort
    state: started
    admin_pw: "{{ vault.infra.checkmk_admin_pw }}"

    omd_auto_restart: 'true'
    omd_config:
      - var: AUTOSTART
        value: on