traefik_admin_services:
  - filename: portainer.yml
    content: |
      http:
        routers:
          portainer:
            rule: "Host(`portainer.{{ traefik_local_domain }}`)"
            entryPoints:
              - https
            service: portainer-service
            tls:
              certResolver: {{ traefik_cert_resolver_name }}
        services:
          portainer-service:
            loadBalancer:
              serversTransport: portainer-transport
              servers:
                - url: "https://{{ hostvars['tools'].ansible_host }}:9443"
        serversTransports:
          portainer-transport:
            insecureSkipVerify: true

  - filename: proxmox.yml
    content: |
      http:
        routers:
          proxmox:
            entryPoints:
              - https
            rule: "Host(`proxmox.{{ traefik_local_domain }}`)"
            service: proxmox-service
            tls:
              certResolver: {{ traefik_cert_resolver_name }}
        services:
          proxmox-service:
            loadBalancer:
              servers:
                - url: "https://{{ hostvars['pve'].ansible_host }}:8006"
              serversTransport: proxmox-tls
        serversTransports:
          proxmox-tls:
            insecureSkipVerify: true

  - filename: traefik_api.yml
    content: |
      http:
        routers:
          dashboard:
            entryPoints:
              - https
            rule: Host(`traefik.{{ traefik_local_domain }}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
            service: api@internal
            tls:
              certResolver: {{ traefik_cert_resolver_name }}
              domains:
                - main: "{{ traefik_local_domain }}"
                  sans:
                    - "*.{{ traefik_local_domain }}"
            middlewares:
              - auth
        middlewares:
          auth:
            basicAuth:
              users:
                - "{{ traefik_dashboard_credentials }}"
