traefik_services: >-
  {{
    (traefik_simple_services | default([]))
    + (traefik_tcp_services | default([]))
    + (traefik_media_services | default([]))
    + (traefik_auth_services | default([]))
    + (traefik_admin_services | default([]))
  }}
