---
librechat_version: "latest"
librechat_compose_dir: /opt/librechat
librechat_data_dir: /opt/librechat/data
librechat_port: 3080
librechat_mcpo_url: "https://mcpo.local.batistela.tech/actual-budget"
librechat_mcpo_api_key: "{{ vault.tools.mcp_mcpo_api_key }}"
librechat_meili_key: "{{ vault.tools.librechat_meili_key }}"
librechat_jwt_secret: "{{ vault.tools.librechat_jwt_secret }}"
librechat_refresh_secret: "{{ vault.tools.librechat_refresh_secret }}"
librechat_creds_key: "{{ vault.tools.librechat_creds_key }}"
librechat_creds_iv: "{{ vault.tools.librechat_creds_iv }}"
